######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 29 13:05:34 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fractionOverloading.h
SOURCES += fractionOverloading.cpp
